spring:
  application:
    name: otc-server
  datasource:
    primary:
      type: io.bhex.base.mysql.BHMysqlDataSource
      url: jdbc:mysql://broker-server-db:3306/exchange_otc?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: broker-server-write
      password: xxxxxx
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 100
        minimum-idle: 10

  redis:
    cluster:
      nodes:
        - broker-server-redis:6379

otc:
  stubDeadline: 8000
  channelInfo:
    - channelName: 'bhServer'
      host: 'bh-server.bluehelix'
      port: 7011
      useSsl: false
    - channelName: 'quoteDataServer'
      host: 'quote-data-service.exchange'
      port: 7063
      useSsl: false

